//! FRI proof transaction type (`0x7c`).
//!
//! Encodes a block-level FRI proof that has been generated by the prover and
//! must be included in the block before regular L2 transactions.
//!
//! RLP encoding: `[chain_id, proof_payload]` (type-byte prefix `0x7c`).
//!
//! The `from` field is always `BOOTLOADER_FORMAL_ADDRESS`; any transaction
//! claiming a different sender is rejected at decode time.

use alloy_primitives::{Address, Bytes};
use alloy_rlp::{Decodable, Encodable, RlpDecodable, RlpEncodable};

use crate::transaction::system::utils::FRI_PROOF_TX_TYPE_ID;

/// Address that must be the signer/initiator of all `0x7c` transactions.
pub const BOOTLOADER_FORMAL_ADDRESS: Address =
    Address::new(hex_literal::hex!("000000000000000000000000000000000000800b"));

/// RLP body of a FRI proof transaction.
#[derive(Debug, Clone, PartialEq, Eq, RlpEncodable, RlpDecodable)]
pub struct FriProofTx {
    /// Chain ID — must match the current network's chain ID.
    pub chain_id: u64,
    /// Opaque proof payload.  Version byte is the first byte:
    /// `0x00` reserved, `0x01` first deployed version.
    pub proof_payload: Bytes,
}

impl FriProofTx {
    /// The EIP-2718 type byte for this transaction type.
    pub const fn tx_type() -> u8 {
        FRI_PROOF_TX_TYPE_ID
    }
}

/// Signed (or rather, implicitly-authorised) envelope for a FRI proof tx.
///
/// There is no ECDSA signature — the sender is hardcoded to
/// `BOOTLOADER_FORMAL_ADDRESS` and validity is enforced structurally.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FriProofTxEnvelope {
    pub inner: FriProofTx,
}

impl FriProofTxEnvelope {
    /// Decode a type-prefixed byte stream.
    ///
    /// Returns `Err` if the type byte is not `FRI_PROOF_TX_TYPE_ID` or if
    /// the inner RLP is malformed.
    pub fn decode_2718(buf: &mut &[u8]) -> Result<Self, alloy_rlp::Error> {
        if buf.is_empty() || buf[0] != FRI_PROOF_TX_TYPE_ID {
            return Err(alloy_rlp::Error::Custom("not a FRI proof transaction"));
        }
        *buf = &buf[1..];
        let inner = FriProofTx::decode(buf)?;
        Ok(Self { inner })
    }

    /// The implicit initiator of all FRI proof transactions.
    pub fn initiator(&self) -> Address {
        BOOTLOADER_FORMAL_ADDRESS
    }

    pub fn chain_id(&self) -> u64 {
        self.inner.chain_id
    }

    pub fn proof_payload(&self) -> &Bytes {
        &self.inner.proof_payload
    }
}
